---
- name: Set login banner
  copy:
    src: motd.txt
    dest: /etc/motd

- name: Update apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  register: result
  until: result is succeeded

- name: Upgrade all packages # noqa package-latest
  apt:
    upgrade: yes
    state: latest
  when: keep_packages_updated
  # tags:
  #  - skip_ansible_lint

- name: Install some packages
  apt:
    name: "{{ pipeline_extra_packages }}"
    state: present
  register: result
  until: result is succeeded

#  - name: Configure smartmontools

- name: "Set hostname to {{ pipeline_hostname }}"
  hostname:
    name: "{{ pipeline_hostname }}"

- name: "Set timezone to {{ pipeline_timezone }}"
  timezone:
    name: "{{ pipeline_timezone }}"

- name: "Permission share directories"
  file:
    path: "{{ item.path }}"
    state: directory
    owner: pipeline-runner
    group: pipeline-runner
    mode: "u=rwX,g=rwX,o=rX"
    recurse: false
  loop: "{{ samba_shares }}"
